FROM postgres:latest
ENV POSTGRES_PASSWORD='example'
ENV POSTGRES_USER='postgres'
# See: https://hub.docker.com/_/postgres Initialization scripts for 
# more details on hoe this works
ADD init.sql /docker-entrypoint-initdb.d
